name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn workspaces run type-check

      - name: Unit tests
        run: yarn workspaces run test
